# Generated by `tokarax` tool
include pkg/karax/prelude

proc createDom(): VNode =
  result = buildHtml(body):
    h1:
      text "Hello World!"
    #[ I
   am
   a
   comment ]#

setRenderer createDom